version: '3.3'
services:
  api:
    build:
      context: ./api
      dockerfile: dev.dockerfile
    image: 'project-dashboard-conversations_api:latest'
    environment:
      - MDB_NAME=platzi-store
      - MDB_PORT=27017
      - MDB_HOST=mongo
      - CDB_NAME=platzi_store
      - CDB_PORT=8091
      - CDB_HOST=couchbase
      - CDB_USER=admin
      - CDB_PWD=admin123
      - NODE_ENV=dev
    deploy:
      labels:
        - traefik.frontend.rule=Host:api.nicobytes.site
        - traefik.enable=true
        - traefik.port=3000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    depends_on:
      - mongo
      - couchbase
    networks:
      - traefik-public
      - default
  couchbase:
    image: couchbase:enterprise-6.0.2
    volumes:
      - couchbase-data:/opt/couchbase/var
    deploy:
      labels:
        - traefik.frontend.rule=Host:db.nicobytes.site
        - traefik.enable=true
        - traefik.port=8091
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - traefik-public
      - default
  mongo:
    image: mongo
  webapp:
    image: 'project-dashboard-c1_webapp:latest'
    build:
      context: ./webapp
      dockerfile: Dockerfile
    deploy:
      labels:
        - traefik.frontend.rule=Host:nicobytes.site
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - traefik-public
      - default

volumes:
  couchbase-data:

networks:
  traefik-public:
    external: true